robot:
  - name: base
    order: 0
    mesh: base.stl
  - name: shoulder
    order: 1
    translate: [0.0, 0.0, 0.163]
    angleAxis: [0, 0, 1]
    mesh: shoulder.stl
  - name: upperarm
    order: 2
    translate: [0.0, 0.138, 0.0]
    rotate: [0.0, 1.57, 0.0]
    angleAxis: [0, 1, 0]
    mesh: upperarm_add.stl
  - name: forearm
    order: 3
    translate: [0.0, -0.131, 0.425]
    angleAxis: [0, 1, 0]
    mesh: forearm_add.stl
  - name: wrist1
    order: 4
    translate: [0.0, 0.0, 0.392]
    rotate: [0.0, 1.57, 0.0]
    angleAxis: [0, 1, 0]
    mesh:  wrist1.stl
  - name: wrist2
    order: 5
    translate: [0.0, 0.127, 0.0]
    angleAxis: [0, 0, 1]
    mesh: wrist2.stl
  - name: wrist3
    order: 6
    translate: [0.0, 0.0, 0.10]
    angleAxis: [0, 1, 0]
    mesh: wrist3.stl

